#development:
#  adapter: mysql2
#  database: sust_main
#  username: sust_matthew
#  password: qwe
#  host: 194.110.173.106
#  encoding: utf8

development:
  database: kargada_development
  adapter: mysql2
  encoding: utf8
  username: ror
  password: pokey123
  host: localhost

test:
  database: kargada_test
  adapter: mysql2
  encoding: utf8
  username: ror
  password: pokey123
  host: localhost

production:
  adapter: mysql2
  database: sust_main
  username: sust_matthew
  password: qwe
  host: 194.110.173.106
  encoding: utf8